### ISSUE TITLE
add packages to docker image

### ISSUE THREAD

**Issue by bolliger32** [RhodiumGroup/docker_images#14]
## apt-get:
* [x] zip

## conda:
* [x] statsmodels==0.9.0

## pip:
* [x] bumpversion==0.5.3
* [x] wheel==0.31.1
* [x] flake8==3.5.0
* [x] tox==3.1.1
* [x] coverage==4.5.1
* [x] PyYAML==3.13
* [x] Sphinx==1.7.5
* [x] pytest==3.6.3
* [x] pytest-cov==2.5.1
* [x] pytest-runner==4.2

**Comment by delgadom** [comment]
Updating the description to include a large number of requested packages
