### ISSUE TITLE
User-defined auto-mounting buckets

### ISSUE THREAD

**Issue by delgadom** [RhodiumGroup/docker_images#19]
Proposal for auto-mounting gcsfuse buckets on the notebook & worker servers on both compute.rhg & compute.impactlab

### Need/use case:

* Right now, the only option is to mount rhg-data on /gcs and nothing else. impactlab.org must have its buckets mounted manually.
* In the longer run, it would be nice to allow different teams to use their own buckets, and for some users to have access to multiple buckets. This would give finer grained permissions control and help prevent an un-navigable explosion of data.

### Proposal

* create a directory in the home folder with a set of key files, each of which is named `~/storage-credentials/[bucket-name].json`
* Modify the `prepare.sh` file on the notebook server to search for such file, and to mount each bucket on `/gcs/[bucket-name]` directories.
* Find some way of modifying the worker `worker_spec.yml` and `prepare.sh` workflow to allow multiple buckets with a mechanism similar to (and a mountpoint exactly matching) the notebook setup

### Upsides

* Multiple buckets could be mounted simultaneously
* Gives us bucket-level permissions control (right now all users must have access to the bucket for that cluster)
* compute.impactlab.org works

### Downsides

* the worker-spec part is kinda tricky
* changing the mount point would cause all the code we've ever written to break

**Comment by delgadom** [comment]
@jgerardsimcock here's another proposal for ya. what do you think? manually mounting impactlab-data every time is driving me a little crazy... 😜

**Comment by jgerardsimcock** [comment]
Ok. This is no problem. I'll do this today.

**Comment by delgadom** [comment]
this  seems kind of hard to me, especially on the worker side. where are you working on this? do you have a branch or PR I could take a look at?

**Comment by delgadom** [comment]
I don't really see why having two copies of a file in the user dir in exchange for all this functionality is such a bad trade-off though! The SQL server is just for the coastal team. I think we can handle an extra file ;)
