### ISSUE TITLE
install new packages

### ISSUE THREAD

**Issue by delgadom** [RhodiumGroup/docker_images#35]
These would be nice:
* [ ] tqdm
* [ ] ~odo~
* [ ] geoalchemy2
* [ ] [python-snappy](https://anaconda.org/conda-forge/python-snappy)

Updates are needed
* [ ] gcsfs
* [ ] fastparquet

**Comment by kemccusker** [comment]
also,

- [ ] gcsfs

**Comment by delgadom** [comment]
closed by #32
