### ISSUE TITLE
notebook and worker images use different linux flavors

### ISSUE THREAD

**Issue by bolliger32** [RhodiumGroup/docker_images#94]
Notebook is Ubuntu and workers are debian, because of the base images (`jupyter/base-notebook` and `continuumio/miniconda3`) used to build the netcdf intermediate images that the notebook and worker images are built on. This results in potential inconsistencies in package availability (e.g. `apt-get libnetcdf` pulls different versions of netcdf for notebook and worker b/c different versions are available for ubuntu and debian). The continuumio/miniconda3 image is just a couple lines installing miniconda3 built on the debian base, so we should just copy those lines and pull from the same ubuntu base that `jupyter/base-notebook` does

**Comment by delgadom** [comment]
Addressed in #104
